apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: ap-northeast-2

iam:
  withOIDC: true

vpc:
  id: "vpc-0e0369f4244706514"
  subnets:
    public:
      ap-northeast-2a:
        id: "subnet-02dba205b2941ae93"
      ap-northeast-2c:
        id: "subnet-017e78922b8afe533"
    private:
      ap-northeast-2a:
        id: "subnet-0bb187f6e55e1b02e"
      ap-northeast-2c:
        id: "subnet-01d0394b7166f4ffd"

managedNodeGroups:
  - name: vamserlike-node-group
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    volumeSize: 30
    privateNetworking: true
    labels:
      role: worker
      project: vamserlike
    tags:
      nodegroup-role: worker
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/eks-demo: "owned"
    iam:
      withAddonPolicies:
        imageBuilder: true
        albIngress: true
        cloudWatch: true
        autoScaler: true

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
